
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'nonassocAFFECTrightANDORleftCOMPAREleftPLUSMINUSleftDIVIDETIMESAFFECT AND COMPARE DIVIDE LPAREN MINUS NAME NUMBER OR PLUS PRINT RPAREN SEMICOLON TIMESstart : statement SEMICOLON start\n    | statement SEMICOLONstatement : PRINT LPAREN expression RPARENstatement : expressionexpression : expression PLUS expressionexpression : expression TIMES expressionexpression : expression MINUS expression\n    | expression DIVIDE expressionexpression : LPAREN expression RPARENexpression : NUMBERexpression : NAMEexpression : expression AND expression\n    | expression OR expressionexpression : expression COMPARE expressionexpression : expression COMPARE expression COMPARE expressionexpression : NAME AFFECT expression'
    
_lr_action_items = {'PRINT':([0,8,],[3,3,]),'LPAREN':([0,3,4,8,9,11,12,13,14,15,16,17,18,31,],[4,9,4,4,4,4,4,4,4,4,4,4,4,4,]),'NUMBER':([0,4,8,9,11,12,13,14,15,16,17,18,31,],[6,6,6,6,6,6,6,6,6,6,6,6,6,]),'NAME':([0,4,8,9,11,12,13,14,15,16,17,18,31,],[7,7,7,7,7,7,7,7,7,7,7,7,7,]),'$end':([1,8,19,],[0,-2,-1,]),'SEMICOLON':([2,5,6,7,21,22,23,24,25,26,27,28,29,30,32,],[8,-4,-10,-11,-9,-5,-6,-7,-8,-12,-13,-14,-16,-3,-14,]),'PLUS':([5,6,7,10,20,21,22,23,24,25,26,27,28,29,32,],[11,-10,-11,11,11,-9,-5,-6,-7,-8,11,11,11,11,11,]),'TIMES':([5,6,7,10,20,21,22,23,24,25,26,27,28,29,32,],[12,-10,-11,12,12,-9,12,-6,12,-8,12,12,12,12,12,]),'MINUS':([5,6,7,10,20,21,22,23,24,25,26,27,28,29,32,],[13,-10,-11,13,13,-9,-5,-6,-7,-8,13,13,13,13,13,]),'DIVIDE':([5,6,7,10,20,21,22,23,24,25,26,27,28,29,32,],[14,-10,-11,14,14,-9,14,-6,14,-8,14,14,14,14,14,]),'AND':([5,6,7,10,20,21,22,23,24,25,26,27,28,29,32,],[15,-10,-11,15,15,-9,-5,-6,-7,-8,15,15,-14,15,-14,]),'OR':([5,6,7,10,20,21,22,23,24,25,26,27,28,29,32,],[16,-10,-11,16,16,-9,-5,-6,-7,-8,16,16,-14,16,-14,]),'COMPARE':([5,6,7,10,20,21,22,23,24,25,26,27,28,29,32,],[17,-10,-11,17,17,-9,-5,-6,-7,-8,17,17,-14,17,-14,]),'RPAREN':([6,7,10,20,21,22,23,24,25,26,27,28,29,32,],[-10,-11,21,30,-9,-5,-6,-7,-8,-12,-13,-14,-16,-14,]),'AFFECT':([7,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,8,],[1,19,]),'statement':([0,8,],[2,2,]),'expression':([0,4,8,9,11,12,13,14,15,16,17,18,31,],[5,10,5,20,22,23,24,25,26,27,28,29,32,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> statement SEMICOLON start','start',3,'p_bloc','calcBase.py',75),
  ('start -> statement SEMICOLON','start',2,'p_bloc','calcBase.py',76),
  ('statement -> PRINT LPAREN expression RPAREN','statement',4,'p_expression_print','calcBase.py',80),
  ('statement -> expression','statement',1,'p_statement_expr','calcBase.py',85),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop_plus','calcBase.py',89),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop_times','calcBase.py',94),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop_divide_and_minus','calcBase.py',99),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop_divide_and_minus','calcBase.py',100),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','calcBase.py',108),
  ('expression -> NUMBER','expression',1,'p_expression_number','calcBase.py',113),
  ('expression -> NAME','expression',1,'p_expression_variable','calcBase.py',118),
  ('expression -> expression AND expression','expression',3,'p_expression_binop_bool','calcBase.py',127),
  ('expression -> expression OR expression','expression',3,'p_expression_binop_bool','calcBase.py',128),
  ('expression -> expression COMPARE expression','expression',3,'p_expression_compare','calcBase.py',136),
  ('expression -> expression COMPARE expression COMPARE expression','expression',5,'p_expression_compare_mul','calcBase.py',150),
  ('expression -> NAME AFFECT expression','expression',3,'p_expression_affect','calcBase.py',166),
]
